services:
  # Main LocalRAG Application
  localrag:
    build:
      context: .
      target: production
    image: localrag:latest
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models  # Direct bind mount for models
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - localrag-network

# volumes:
#   localrag_models:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./models

networks:
  localrag-network:
    driver: bridge